{{- if .Values.mcp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openwebui-platform.fullname" . }}-mcp
  labels:
    {{- include "openwebui-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp
spec:
  {{- if not .Values.mcp.autoscaling.enabled }}
  replicas: {{ .Values.mcp.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "openwebui-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mcp
  template:
    metadata:
      labels:
        {{- include "openwebui-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mcp
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openwebui-platform.serviceAccountName" . }}
      securityContext:
        fsGroup: 2000
      containers:
        - name: mcp-server
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
              - ALL
          image: "{{ .Values.mcp.image.repository }}:{{ .Values.mcp.image.tag }}"
          imagePullPolicy: {{ .Values.mcp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.mcp.service.targetPort }}
              protocol: TCP
          env:
            - name: MCP_SERVER_HOST
              value: "0.0.0.0"
            - name: MCP_SERVER_PORT
              value: "{{ .Values.mcp.service.targetPort }}"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "openwebui-platform.fullname" . }}-secrets
                  key: database-url
            - name: REDIS_URL
              value: "redis://{{ .Release.Name }}-redis-master:6379"
            - name: VECTOR_DB_URL
              value: "http://{{ .Release.Name }}-qdrant:6333"
            - name: GRAPH_DB_URL
              value: "bolt://{{ .Release.Name }}-neo4j:7687"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.mcp.resources | nindent 12 }}
      {{- with .Values.mcp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mcp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mcp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}