{{- if .Values.security.rbac.create }}
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openwebui-platform.serviceAccountName" . }}
  labels:
    {{- include "openwebui-platform.labels" . | nindent 4 }}
  {{- with .Values.security.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true

---
# Cluster Role for OpenWebUI Platform
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "openwebui-platform.fullname" . }}
  labels:
    {{- include "openwebui-platform.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]

---
# Cluster Role Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "openwebui-platform.fullname" . }}
  labels:
    {{- include "openwebui-platform.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "openwebui-platform.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "openwebui-platform.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

---
# Role for namespace-specific permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "openwebui-platform.fullname" . }}
  labels:
    {{- include "openwebui-platform.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
# Role Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "openwebui-platform.fullname" . }}
  labels:
    {{- include "openwebui-platform.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "openwebui-platform.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "openwebui-platform.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}