apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openwebui-platform.fullname" . }}-secrets
  labels:
    {{- include "openwebui-platform.labels" . | nindent 4 }}
type: Opaque
data:
  webui-secret-key: {{ .Values.openwebui.env.WEBUI_SECRET_KEY | b64enc | quote }}
  database-url: {{ include "openwebui-platform.databaseURL" . | b64enc | quote }}
  {{- if .Values.openwebui.env.OPENAI_API_KEY }}
  openai-api-key: {{ .Values.openwebui.env.OPENAI_API_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.openwebui.env.ANTHROPIC_API_KEY }}
  anthropic-api-key: {{ .Values.openwebui.env.ANTHROPIC_API_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.neo4j.neo4j.password }}
  neo4j-password: {{ .Values.neo4j.neo4j.password | b64enc | quote }}
  {{- end }}